version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: file_service_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: file-service
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: file_service_storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
